### PR TITLE
Rework as contao manager plugin, add PHP 8 Support and more

### LINKED ISSUE #14: PHP 8 compatibility
Any chances that this modules become PHP 8 ready?

```
- Root composer.json requires cboelter/contao-lead-optin ^1.3 -> satisfiable by cboelter/contao-lead-optin[1.3].
- cboelter/contao-lead-optin 1.3 requires php ^5.6 || ^7.0 -> your php version (8.0.17.0) does not satisfy that requirement.
```

### PR DESCRIPTION
**Pull request by zoglo**
This pull request reworks the bundle as a contao manager plugin and should be backwards compatible with the old version:

<h3>Changes</h3>

- unlocked PHP8 and added minimum compatibility of Contao 4.9 into composer.json https://github.com/cboelter/contao-leads-optin/commit/a51e51c4b77c164c75562071d6bb93a7f51c0f61 https://github.com/cboelter/contao-leads-optin/commit/49aecbfe133abb35a4ebbfc2ba5db9cd5a53ecdd https://github.com/cboelter/contao-leads-optin/commit/08ae0e32bf2264a5cc0f3d920c621c6d7dffe9e6

- changed bundle structure and registered it as a manager plugin https://github.com/cboelter/contao-leads-optin/commit/c000216e6c243b4c7a8b335a071390cec0a8b55e https://github.com/cboelter/contao-leads-optin/commit/4b4a4e897143caa9e76b0bb83c81819423e9c7b3 https://github.com/cboelter/contao-leads-optin/commit/2f5ead99013eb919fd68df273fe690ab37774f5b https://github.com/cboelter/contao-leads-optin/commit/a51e51c4b77c164c75562071d6bb93a7f51c0f61

- changed language format to xliff and fixed german typos and grammar https://github.com/cboelter/contao-leads-optin/commit/5a0014fb1cd644dce7fe5e58a3a0ba7624096a81

- added usages, removed deprecated patchwork/UTF8, CS and refactoring within classes

____

<h3>Additions</h3>

- added an onLeadOptinSuccessHook and an onOptInSuccess-method (for inheritance reasons) to Optin https://github.com/cboelter/contao-leads-optin/commit/3852f2b06d835c6ccc8ced3506e3490b6699e1b7

- added complete english translation https://github.com/cboelter/contao-leads-optin/commit/5a0014fb1cd644dce7fe5e58a3a0ba7624096a81

____

Notes:
- I did change the branch-alias to ```"dev-develop": "1.4.x-dev"``` as I've thought that you might release this as a version 1.4 rather than a 2.0.

____

Will also fix https://github.com/cboelter/contao-leads-optin/issues/14

### CODE REVIEW

**Comment by cboelter** [comment]
Oh thats awesome :-) thanks for the PR. I'm currently out of office until end of november, but I will release the version immediatly if I'am back!

**Comment by rabauss** [comment]
Thanks for this PR! 🚀 
Everyone who wants to use the forked version now - attention you need to add the repo AND you need to rename the package!
Unfortunately, this realization cost me a lot of time today 😢 

```json
"require": {
  "oveleon/contao-leads-optin": "1.4.x-dev",
  }

  "repositories": [
  {
    "type": "vcs",
    "url": "https://github.com/oveleon/contao-leads-optin"
  }
]
```

**Comment by zoglo** [comment]
@cboelter 

I did add a little bit more to this pull request:

___
<h3>Additions</h3>

- Added a possibility to attach files for opt-in success notifications 5b8b008a9d595777e8bfecc70d9e27143765498f

- Throw an opt-in error message when no token was parsed (UX-Improvement) da4c09ed7751059919e3539c5ae7e52f83bfcf11

- Add context to onLeadOptinSuccess-Hook 9c1485264756de04f4cf3b533f29070a2ea9a0c6

<h3>Bugfixes</h3>

- Change optin_ip to varchar(64) to support IPv6 98e6e6b93dcf0b0d2d2d39dfe5a877666953f2f6 (fixes #11 )

- Consider languages within opt-in notifications 5ae12686266ccb258b72b58df77fa559e4953f6f (fixes #7 )

___ 

### An explanation of the new additions:

#### File attachments
Currently, it is not possible to add file attachments via context so I did rework the messaging with parts of the notification center. This might be changed with the planned v2.0 of the Notification Center. I can help you if there may be any changes in the future. They can be added by manipulating $arrTokens through the Hook or the onOptinSuccessMethod by populating:
```$arrTokens['optin_attachments']``` as seen [here](https://github.com/oveleon/contao-leads-optin/blob/6b8bcf6f43514dd9e19bf645ddb4ad557d9a7dec/src/Notification/OptinMessage.php#L42).

#### Opt-in error message
If no token has been parsed, nothing would be shown within the page and it was blank. This should improve user experience

#### Context to onLeadOptinSuccess-Hook
In case people need parts of the settings, they are able to read them through the newly added Hook.

**Comment by kroerig** [comment]
Please merge. This packages blocks upgrading Contao installations to PHP 8.x

**Comment by cboelter** [comment]
@zoglo first of all thanks for this massive PR :-) I will now check it. I think all these changes are a Version 2.0 worth :-)

**Pull request merged**
